// <auto-generated />
using System;
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505140202_PocetnaMigracija")]
    partial class PocetnaMigracija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC.Models.CitalackaGrupa", b =>
                {
                    b.Property<int>("GrupaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupaId"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaksimalanBrojClanova")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipGrupe")
                        .HasColumnType("int");

                    b.Property<string>("Zanr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrupaId");

                    b.ToTable("CitalackaGrupa", (string)null);
                });

            modelBuilder.Entity("MVC.Models.ClanstvoGrupe", b =>
                {
                    b.Property<int>("ClanstvoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClanstvoId"));

                    b.Property<DateTime>("DatumPridruzivanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupaId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("StatusClanstva")
                        .HasColumnType("int");

                    b.HasKey("ClanstvoId");

                    b.HasIndex("GrupaId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("ClanstvoGrupe", (string)null);
                });

            modelBuilder.Entity("MVC.Models.Knjiga", b =>
                {
                    b.Property<int>("KnjigaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KnjigaId"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojStranica")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zanr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KnjigaId");

                    b.ToTable("Knjiga", (string)null);
                });

            modelBuilder.Entity("MVC.Models.KnjigaGrupa", b =>
                {
                    b.Property<int>("KnjigaGrupaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KnjigaGrupaId"));

                    b.Property<int>("GrupaId")
                        .HasColumnType("int");

                    b.Property<int>("KnjigaId")
                        .HasColumnType("int");

                    b.HasKey("KnjigaGrupaId");

                    b.HasIndex("GrupaId");

                    b.HasIndex("KnjigaId");

                    b.ToTable("KnjigaGrupa", (string)null);
                });

            modelBuilder.Entity("MVC.Models.Komentar", b =>
                {
                    b.Property<int>("KomentarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KomentarId"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumKomentara")
                        .HasColumnType("datetime2");

                    b.Property<int>("SadrzajId")
                        .HasColumnType("int");

                    b.Property<int>("StatusKomentara")
                        .HasColumnType("int");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KomentarId");

                    b.HasIndex("AutorId");

                    b.HasIndex("SadrzajId");

                    b.ToTable("Komentar", (string)null);
                });

            modelBuilder.Entity("MVC.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<string>("Biografija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LokacijaX")
                        .HasColumnType("float");

                    b.Property<double>("LokacijaY")
                        .HasColumnType("float");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilnaSlika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusNaloga")
                        .HasColumnType("int");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("MVC.Models.Profil", b =>
                {
                    b.Property<int>("ProfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfilId"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisProfila")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfilId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Profil", (string)null);
                });

            modelBuilder.Entity("MVC.Models.SadrzajGrupe", b =>
                {
                    b.Property<int>("SadrzajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SadrzajId"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupaId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusSadrzaja")
                        .HasColumnType("int");

                    b.Property<int>("TipSadrzaja")
                        .HasColumnType("int");

                    b.HasKey("SadrzajId");

                    b.HasIndex("AutorId");

                    b.HasIndex("GrupaId");

                    b.ToTable("SadrzajGrupe", (string)null);
                });

            modelBuilder.Entity("MVC.Models.ZahtjevZaPristup", b =>
                {
                    b.Property<int>("ZahtjevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZahtjevId"));

                    b.Property<DateTime>("DatumZahtjeva")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupaId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("StatusZahtjeva")
                        .HasColumnType("int");

                    b.HasKey("ZahtjevId");

                    b.HasIndex("GrupaId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("ZahtjevZaPristup", (string)null);
                });

            modelBuilder.Entity("MVC.Models.ClanstvoGrupe", b =>
                {
                    b.HasOne("MVC.Models.CitalackaGrupa", "CitalackaGrupa")
                        .WithMany()
                        .HasForeignKey("GrupaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MVC.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CitalackaGrupa");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MVC.Models.KnjigaGrupa", b =>
                {
                    b.HasOne("MVC.Models.CitalackaGrupa", "CitalackaGrupa")
                        .WithMany()
                        .HasForeignKey("GrupaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MVC.Models.Knjiga", "Knjiga")
                        .WithMany()
                        .HasForeignKey("KnjigaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CitalackaGrupa");

                    b.Navigation("Knjiga");
                });

            modelBuilder.Entity("MVC.Models.Komentar", b =>
                {
                    b.HasOne("MVC.Models.Korisnik", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MVC.Models.SadrzajGrupe", "SadrzajGrupe")
                        .WithMany()
                        .HasForeignKey("SadrzajId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("SadrzajGrupe");
                });

            modelBuilder.Entity("MVC.Models.Profil", b =>
                {
                    b.HasOne("MVC.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("MVC.Models.SadrzajGrupe", b =>
                {
                    b.HasOne("MVC.Models.Korisnik", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MVC.Models.CitalackaGrupa", "CitalackaGrupa")
                        .WithMany()
                        .HasForeignKey("GrupaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("CitalackaGrupa");
                });

            modelBuilder.Entity("MVC.Models.ZahtjevZaPristup", b =>
                {
                    b.HasOne("MVC.Models.CitalackaGrupa", "CitalackaGrupa")
                        .WithMany()
                        .HasForeignKey("GrupaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MVC.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CitalackaGrupa");

                    b.Navigation("Korisnik");
                });
#pragma warning restore 612, 618
        }
    }
}
